import type { Metadata } from "next";
import { Nunito, Raleway} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ContactOptions from "@/components/ContactOptions";
import Header from "@/components/Header";
import pages from "@/static/data/pages";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito"
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${raleway.variable} antialiased`}
      >

        <Header />

        <main>
          {children}
        </main>

        <footer>
          <div className="container">
            <div className="footer-item">
              <h3 className="footer-item-title">Charity CDS Abuja</h3>
              <p className="regular-text">We are dedicated to making a positive impact in our community through various charitable activities and programs.</p>
            </div>
            <div className="footer-item">
              <h3 className="footer-item-title">Quick Links</h3>
              <ul className="quick-links">
                {
                  pages.map((page) => (
                    <li key={page.title} className="quick-link"><Link href={page.url}>{page.title}</Link></li>
                  ))
                }
              </ul>
            </div>
            <div className="footer-item">
              <h3 className="footer-item-title">Contact Us</h3>
              <ContactOptions />
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
